# Generated by Django 6.0 on 2025-12-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_type', models.CharField(choices=[('Freelance', 'Freelance / Gig'), ('Contract', 'Short-Term Contract'), ('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time'), ('Internship', 'Internship / Attachment')], default='Freelance', max_length=20)),
                ('category', models.CharField(choices=[('Tech', 'Software Development & IT'), ('Design', 'Graphic Design & Creative'), ('Writing', 'Content Writing & Translation'), ('Admin', 'Virtual Assistant & Data Entry'), ('Marketing', 'Digital Marketing & Sales'), ('Video', 'Video Editing & Animation')], default='Tech', max_length=20)),
                ('experience_level', models.CharField(choices=[('Entry', 'Entry Level (Beginner)'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Entry', max_length=20)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
