# Generated by Django 6.0 on 2025-12-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Looking for a Logo Designer'", max_length=200)),
                ('description', models.TextField(help_text='Detailed requirements, deliverables, and skills needed.')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Project budget in KES', max_digits=10)),
                ('job_type', models.CharField(choices=[('Freelance', 'Freelance / One-off'), ('Contract', 'Contract (Long-term)'), ('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time'), ('Internship', 'Internship / Attachment')], default='Freelance', max_length=20)),
                ('category', models.CharField(choices=[('Tech', 'Software Dev & IT'), ('Design', 'Graphic Design & Creative'), ('Writing', 'Content Writing & Translation'), ('Admin', 'Virtual Assistant & Data Entry'), ('Marketing', 'Digital Marketing & Sales'), ('Video', 'Video Editing & Animation')], default='Tech', max_length=20)),
                ('experience_level', models.CharField(choices=[('Entry', 'Entry Level (Beginner)'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Entry', max_length=20)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
