# Generated by Django 6.0 on 2025-12-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Tech', 'Software Development & IT'), ('Design', 'Graphic Design & Creative'), ('Writing', 'Content Writing & Translation'), ('Admin', 'Virtual Assistant & Data Entry'), ('Marketing', 'Digital Marketing & Sales'), ('Video', 'Video Editing & Animation')], default='Tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Freelance', 'Freelance / Gig'), ('Contract', 'Short-Term Contract'), ('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time'), ('Internship', 'Internship / Attachment')], default='Freelance', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
