# Generated by Django 6.0 on 2025-12-07 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='Project budget in KES', max_digits=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='Detailed requirements, deliverables, and skills needed.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(help_text="e.g., 'Looking for a Logo Designer'", max_length=200),
        ),
    ]
