# Generated by Django 5.2.8 on 2025-12-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Job must be approved by admin before being visible.'),
        ),
    ]
