# Generated by Django 5.2.8 on 2025-12-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_avatar.png', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, help_text='Upload your CV/Resume (PDF/Docx)', null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_employer_verified',
            field=models.BooleanField(default=False, help_text='Designates if this employer can post jobs.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer')], default='job_seeker', max_length=20),
        ),
    ]
