# Generated by Django 5.2.8 on 2025-12-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_avatar_profile_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Designates if the user has paid for premium access.'),
        ),
    ]
