# Generated by Django 5.2.8 on 2025-12-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_facebook',
            field=models.URLField(blank=True, help_text='Facebook Page URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_linkedin',
            field=models.URLField(blank=True, help_text='LinkedIn Company Page URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_twitter',
            field=models.URLField(blank=True, help_text='Twitter/X Profile URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, help_text='e.g. https://www.yourcompany.com'),
        ),
    ]
